myano/jenni

README.md, jenni
=> Refuse to start if run as root (euid=0)

modules/tell.py
Ported from willie.
Ref.: https://github.com/embolalia/willie/commit/858e7ec3efac0e8ff17cce4e4148645473bcb832
=> Make tell thread-safe by adding locks everywhere

modules/arxiv.py, modules/dinner.py, modules/oed.py, modules/url.py, modules/youtube.py
the arxiv module on myano/jenni was from an older dump, and it doesn't work very well
=> adding the arXiv module

bot.py, irc.py, jenni, modules/adminchannel.py, modules/banned_words.py, modules/startup.py
- Added tracking of modes for ops/hops/voices to Jenni
- Added banned words module that will warn and ban based on banned words configuration file
- Moved banned words and limit to jenni config
- Added defaults in jenni runner
- Made banned words per channel
- Made banned words regex capable
=> [dev-ban-words] Add modes and ban words

bot.py
=> Fixes Bot init having a wrong argument, sending nickserv pass instead of serverpass.

modules/github_stats.py
- Search repos
- Get number of and top 5 PRs
- Get number of and top 5 contributors (with number of contributions)
=> [dev-github-stats] Basic github commands

modules/wikiquote.py
- Limited to one of accepted categories
- You can choose at random from all categories or input one
=> [dev-wikiquote] Added random wikiquote

modules/sasl.py
Thanks to @kaneda for helping me fix this.
=> Fixes trying to do SASL auth without credentials being supplied in config

modules/github_stats.py
- Added functionality to search for users and get user info
=> [dev-github-updates] Added user functions

.gitignore, CREDITS, README.md, modules/adminchannel.py, modules/info.py
- First round of updates, next to update the wiki with all available commands, examples, and descriptions
=> [dev-update-docs] First round

configs.py, jenni, modules/admin.py
- Added reload command to jenni for owners to reload configs
=> [dev-109] Reload command for owners

modules/weather.py
the heat index formula used is valid for T >= 80F and RH >= 40%. reported heat index values outside of this range are nonsensical
=> fix heat index in f_weather

irc.py, modules/startup.py
- Record when auth is attempted so that we don't try repeatedly for no reason, this causes disconnects on some IRC servers
=> [dev-157] Stop multiple auth attempts

jenni
- Report errors related to config directories
- Don't complete initialization if no config files are found at all, for whatever reason
=> [dev-158] Added safety around configs

configs.py
=> [dev-109-fix] Import sys

modules/youtube.py
=> [dev-170] Added youtube functionality

modules/rand.py
I changed bot answers like "jenni.say(str(input.nick) + ": blablabla")" to "jenny.reply("blablabla")".
=> changing jenni.say to jenny.reply

modules/magic8Ball.py
Simple magic 8 ball module, random answer from 20 possible answers.
.magic8Ball or .m8b
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/myano/jenni/189)
=> Added magic 8 ball module

modules/magic8Ball.py
Squashed commits:
Converted magic8Ball.py to 4 space tabs rather than tab char
[3642839] Fixed usage of randint() (randint() is inclusive)
[a5f3edb] Magic8Ball module: Implemented per day answers for a given question
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/myano/jenni/191)
=> magic8Ball module: per day answers

modules/magic_8_ball.py
- Datetime was ruining the random seed for a given input
- Removed whitespace
=> [dev-fix-m8b] Fixed magic 8ball

jenni, modules/chicken_reply.py
"what?" "chicken butt" 
Disabled by default
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/myano/jenni/196)
=> Chicken_reply module

modules/spotify.py
- Bold information being returned by spotify.
- Return information on one line only.
- Add release year for fun.
- Add availability information for albums, again for fun and trivia.
- Add myself to copyright notice
- Utilises the full list of artists returned from Spotify
- Gramatically correct listing of artists.
=> Spotify module changes

modules/spotify.py
- Proper error handling
- Trigger anywhere on word boundaries, but don't trigger if there's
a space between the tokens
- Make "spotify" and object type case-insensitive
=> Spotify fixes

modules/slap.py
added additional verbs to `slap.py`
=> added additional verbs

modules/twitter.py
fixes #233 by adding an appropriate response when a 401 is returned (private tweets)
additionally fixes a bug where the status from `initialize_keys` is not properly handled
=> fix twitter.py
